<a href="https://colab.research.google.com/github/Bibhuti-MLAI/Python-Coding-Interview/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import model_selection
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [47]:
df = pd.read_csv("/content/drive/MyDrive/Python cx/Feature Engineering/customer.csv")

In [48]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [49]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [50]:
df = df.iloc[:,2:]

In [51]:
df.head(5)

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

Ordinal Encoding

In [52]:
from sklearn.preprocessing import OrdinalEncoder

In [53]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1])

In [54]:
X_train

     review education
45     Poor        PG
12     Poor    School
7      Poor    School
25     Good    School
44  Average        UG
38     Good    School
20  Average    School
22     Poor        PG
40     Good    School
24  Average        PG
15     Poor        UG
46     Poor        PG
49     Good        UG
29  Average        UG
2      Good        PG
37  Average        PG
36     Good        UG
28     Poor    School
33     Good        PG
48     Good        UG
9      Good        UG
35     Poor    School
42     Good        PG
30  Average        UG
26     Poor        PG
32  Average        UG
21  Average        PG
41     Good        PG
14     Poor        PG
4   Average        UG
27     Poor        PG
3      Good        PG
43     Poor        PG
1      Poor        UG
0   Average    School
13  Average    School
8   Average        UG

In [55]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [56]:
X_train=oe.transform(X_train)
X_test = oe.transform(X_test)

In [57]:
X_train

array([[0., 2.],
       [0., 0.],
       [0., 0.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.]])

In [58]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [59]:
from sklearn.preprocessing import LabelEncoder

In [60]:
lb =LabelEncoder()

In [61]:
lb.fit(y_train)

LabelEncoder()

In [62]:
y_train = lb.transform(y_train)
y_test = lb.transform(y_test)

In [63]:
y_train

array([1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])