<a href="https://colab.research.google.com/github/Bibhuti-MLAI/Python-Coding-Interview/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import model_selection
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [46]:
df = pd.read_csv("/content/drive/MyDrive/Python cx/Feature Engineering/customer.csv")

In [47]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [48]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [49]:
df = df.iloc[:,2:]

In [50]:
df.head(5)

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

Ordinal Encoding

In [51]:
from sklearn.preprocessing import OrdinalEncoder

In [52]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1])

In [53]:
X_train

     review education
39     Poor        PG
20  Average    School
42     Good        PG
25     Good    School
21  Average        PG
0   Average    School
5   Average    School
3      Good        PG
36     Good        UG
22     Poor        PG
12     Poor    School
6      Good    School
29  Average        UG
31     Poor    School
41     Good        PG
49     Good        UG
37  Average        PG
17     Poor        UG
10     Good        UG
43     Poor        PG
44  Average        UG
30  Average        UG
18     Good    School
32  Average        UG
9      Good        UG
47     Good        PG
46     Poor        PG
34  Average    School
19     Poor        PG
38     Good    School
4   Average        UG
15     Poor        UG
23     Good    School
26     Poor        PG
27     Poor        PG
24  Average        PG
13  Average    School

In [54]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [55]:
X_train=oe.transform(X_train)
X_test = oe.transform(X_test)

In [56]:
X_train

array([[0., 2.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [1., 2.],
       [1., 0.],
       [1., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [1., 0.]])

In [57]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [58]:
from sklearn.preprocessing import LabelEncoder

In [59]:
lb =LabelEncoder()

In [60]:
lb.fit(y_train)

LabelEncoder()

In [61]:
y_train = lb.transform(y_train)
y_test = lb.transform(y_test)

In [62]:
y_train

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0])

One hot encoding

In [63]:
df = pd.read_csv("/content/drive/MyDrive/Python cx/Feature Engineering/cars.csv")

In [64]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [65]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [66]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [67]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [68]:
from sklearn.preprocessing import OneHotEncoder
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,:-1],test_size=0.2,random_state=45)

In [69]:
X_train

           brand  km_driven    fuel         owner
5181     Renault      50000  Diesel   First Owner
2024        Tata      74000  Petrol  Second Owner
6203       Skoda      40000  Diesel   First Owner
7026        Tata      28000  Petrol  Second Owner
5837        Tata       5000  Petrol   First Owner
...          ...        ...     ...           ...
3616        Tata      28000  Petrol  Second Owner
6012  Volkswagen      54327  Petrol  Second Owner
5763     Hyundai      76460  Diesel   First Owner
6558       Volvo      20000  Diesel   First Owner
7115        Tata     120000  Diesel  Second Owner

[6502 rows x 4 columns]

In [73]:
ohe = OneHotEncoder(drop = 'first')

In [74]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [75]:
X_test_new = ohe.fit_transform(X_test[['fuel','owner']]).toarray()

In [76]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

In [77]:
X_train_new.shape

(6502, 7)

In [78]:
counts = df['brand'].value_counts()

In [79]:
threshold =100

In [81]:
repl=counts[counts <= threshold].index

In [82]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
2625,False,False,False,False,False,False,True,False,False,False,False,False,False
2821,False,False,False,False,False,False,False,False,False,True,False,False,False
6641,False,False,False,True,False,False,False,False,False,False,False,False,False
4239,False,False,False,False,False,False,False,False,False,False,True,False,False
285,False,False,False,False,False,False,False,False,False,True,False,False,False