<a href="https://colab.research.google.com/github/Bibhuti-MLAI/Python-Coding-Interview/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import model_selection
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Python cx/Feature Engineering/customer.csv")

In [3]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [5]:
df = df.iloc[:,2:]

In [6]:
df.head(5)

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

Ordinal Encoding

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1])

In [9]:
X_train

     review education
32  Average        UG
40     Good    School
2      Good        PG
9      Good        UG
47     Good        PG
22     Poor        PG
49     Good        UG
37  Average        PG
12     Poor    School
41     Good        PG
0   Average    School
16     Poor        UG
36     Good        UG
24  Average        PG
8   Average        UG
20  Average    School
35     Poor    School
48     Good        UG
13  Average    School
17     Poor        UG
7      Poor    School
6      Good    School
42     Good        PG
19     Poor        PG
43     Poor        PG
30  Average        UG
4   Average        UG
1      Poor        UG
5   Average    School
38     Good    School
45     Poor        PG
28     Poor    School
44  Average        UG
18     Good    School
39     Poor        PG
31     Poor    School
26     Poor        PG

In [10]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [11]:
X_train=oe.transform(X_train)
X_test = oe.transform(X_test)

In [12]:
X_train

array([[1., 1.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [0., 1.],
       [2., 1.],
       [1., 2.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [0., 2.]])

In [13]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
lb =LabelEncoder()

In [16]:
lb.fit(y_train)

LabelEncoder()

In [17]:
y_train = lb.transform(y_train)
y_test = lb.transform(y_test)

In [18]:
y_train

array([1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0])

One hot encoding

In [19]:
df = pd.read_csv("/content/drive/MyDrive/Python cx/Feature Engineering/cars.csv")

In [20]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [21]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [22]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [23]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [24]:
from sklearn.preprocessing import OneHotEncoder
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,:-1],test_size=0.2,random_state=45)

In [25]:
X_train

           brand  km_driven    fuel         owner
5181     Renault      50000  Diesel   First Owner
2024        Tata      74000  Petrol  Second Owner
6203       Skoda      40000  Diesel   First Owner
7026        Tata      28000  Petrol  Second Owner
5837        Tata       5000  Petrol   First Owner
...          ...        ...     ...           ...
3616        Tata      28000  Petrol  Second Owner
6012  Volkswagen      54327  Petrol  Second Owner
5763     Hyundai      76460  Diesel   First Owner
6558       Volvo      20000  Diesel   First Owner
7115        Tata     120000  Diesel  Second Owner

[6502 rows x 4 columns]

In [26]:
ohe = OneHotEncoder(drop = 'first')

In [27]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [28]:
X_test_new = ohe.fit_transform(X_test[['fuel','owner']]).toarray()

In [29]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

In [30]:
X_train_new.shape

(6502, 7)

In [31]:
counts = df['brand'].value_counts()

In [32]:
threshold =100

In [33]:
repl=counts[counts <= threshold].index

In [34]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
410,False,False,False,False,False,False,False,False,False,False,False,False,True
4537,False,False,False,False,True,False,False,False,False,False,False,False,False
5023,False,False,False,False,False,False,False,False,False,True,False,False,False
3113,False,False,False,False,True,False,False,False,False,False,False,False,False
4164,False,False,False,False,False,True,False,False,False,False,False,False,False

Columns Transformer

In [35]:
df = pd.read_csv("/content/drive/MyDrive/Python cx/Feature Engineering/covid_toy.csv")

In [36]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [37]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.impute import SimpleImputer

In [38]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [39]:
from warnings import simplefilter
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])


x_test_fever = si.fit_transform(X_test[['fever']])

X_train_new.shape

(6502, 7)